README.md

프로젝트 소개 작성

---

client/Projects/CustomNetwork/.swiftlint.yml
client/Projects/CustomNetwork/CustomNetwork/CustomNetwork.swift
client/Projects/CustomSocket/.swiftlint.yml
client/Projects/CustomSocket/CustomSocket/CustomSocket.swift
client/Projects/OpenList/.swiftlint.yml
client/Projects/OpenList/OpenList.xcodeproj/project.pbxproj
client/Projects/OpenList/OpenList/Domain/Entites/CheckListTableItem.swift
client/Projects/OpenList/OpenList/Extension/Publisher+Operator.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTableScene/CheckListTableAction.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTableScene/CheckListTableRouter.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTableScene/CheckListTableViewController.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTableScene/CheckListTableViewFactory.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTableScene/CheckListTableViewModel.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTableScene/View/CheckListTableCell.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTableScene/View/GaugeView.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/TabBarViewFactory.swift

- #8 
- Layer는 AutoLayout이 적용이 안되다 보니 위치를 계산해줘야 하여 하드코딩된 부분이 있는게 아쉽습니다.
- 디자인 시스템을 아직 정의하지 않아 UIColor에도 하드 코딩이 들어가 있습니다.
- 디자인 시스템 구현 후 리팩토링 할 예정입니다.
- 그라데이션을 적용할 때 `The layer is using dynamic shadows which are expensive to render. If possible try setting 'shadowPath', or pre-rendering the shadow into an image and putting it under the layer` 라는 문구가 떴습니다.
- 이는 렌더링 비용이 많이 들어 shadowPath를 지정해 주라는 이슈였습니다.
- `layer.shadowPath = UIBezierPath()` 이런 식으로 `UIBezierPath`를 지정해주어 해결하였습니다.
| 실행 1 | 실행 2|
|-|-|
|<img width="300" src="https://github.com/boostcampwm2023/iOS10-OpenList/assets/53855302/927c40f6-af25-43ea-8176-214f4ceab618">|<img width="300" src="https://github.com/boostcampwm2023/iOS10-OpenList/assets/53855302/9700b1eb-7d72-473f-ae2e-de5821206c27">|
- na

사용자는 생성한 체크리스트를 리스트형태로 볼수 있다.

---

server/package.json
server/src/users/users.controller.spec.ts
server/src/users/users.service.spec.ts
server/test/test-common.module.ts

- #31 
**`테스트시 src와 test 경로를 찾지 못하는 문제`**
- <img width="635" alt="스크린샷 2023-11-15 오후 8 25 31" src="https://github.com/boostcampwm2023/iOS10-OpenList/assets/51476641/bf8224fa-6aa3-4536-b329-9fb6d4e52283">
**`테스트시 레포지토리를 찾지 못하는 문제`**
- <img width="643" alt="스크린샷 2023-11-15 오후 8 29 10" src="https://github.com/boostcampwm2023/iOS10-OpenList/assets/51476641/7a48d55e-56fb-4dce-89f4-db88b8a52da7">
**`테스트시 src와 test 경로를 찾지 못하는 문제`**
- pakage.json에서 jest 설정에 경로 설정 추가
```json 
"moduleNameMapper": {
"^src/(.*)$": "<rootDir>/$1",
"^test/(.*)$": "<rootDir>/../test/$1"
},
```
- https://stackoverflow.com/questions/56703570/unable-to-run-tests-because-nest-cannot-find-a-module
**`테스트시 레포지토리를 찾지 못하는 문제`**
- test-common.module.ts에 디비 관련 설정 넣은 뒤, 테스트 모듈에 주입
```ts
// users.controller.spec.ts …
```

[Server] 유닛 테스트 환경 세팅

---

server/src/app.module.ts
server/src/users/entities/user.entity.ts
server/src/users/users.controller.spec.ts
server/src/users/users.controller.ts
server/src/users/users.module.ts
server/src/users/users.service.spec.ts
server/src/users/users.service.ts
server/test/test-common.module.ts

[Server] Users resource 이름 변경

---

client/Projects/CustomNetwork/.swiftlint.yml
client/Projects/CustomNetwork/CustomNetwork.xcodeproj/project.pbxproj
client/Projects/CustomNetwork/CustomNetwork.xcodeproj/xcshareddata/xcschemes/CustomNetworkTests.xcscheme
client/Projects/CustomNetwork/CustomNetwork/CustomNetwork.swift
client/Projects/CustomNetwork/CustomNetwork/CustomSession.swift
client/Projects/CustomNetwork/CustomNetwork/NetworkError.swift
client/Projects/CustomNetwork/CustomNetwork/NetworkService.swift
client/Projects/CustomNetwork/CustomNetwork/RequestInterceptor.swift
client/Projects/CustomNetwork/CustomNetwork/RequestRetrier.swift
client/Projects/CustomNetwork/CustomNetwork/URLRequestBuilder.swift
client/Projects/CustomNetwork/CustomNetworkTests/Mock/MockURLProtocol.swift
client/Projects/CustomNetwork/CustomNetworkTests/NetworkServiceTests.swift
client/Projects/OpenList/OpenList.xcodeproj/project.pbxproj
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTableScene/View/CheckListTableCell.swift

- #28 
- 프로젝트에 종속적이지 않고 범용적으로 사용할 수 있는 네트워크 모듈 구성에 대한 고민
- 네트워크 모듈에서 어떤 것을 테스트 해야 할지에 대한 고민
- MockURLProtocol 을 이용한 네트워크 테스트
- 5개의 테스트 중 5개 통과

네트워크 모듈 구성

---

.github/workflows/main.yml

chore: ci/cd를 위한 main.yml 추가

---

client/Projects/OpenList/OpenList/Data/Repositories/DefaultCheckListRepository.swift

체크리스트 진행률 오류 수정

---

client/Projects/CustomNetwork/CustomNetwork/NetworkService.swift
client/Projects/CustomNetwork/CustomNetwork/URLRequestBuilder.swift
client/Projects/CustomNetwork/CustomNetworkTests/NetworkServiceTests.swift
client/Projects/OpenList/OpenList/Data/Repositories/DefaultAuthRepository.swift

네트워크 모듈 수정

---

client/Projects/OpenList/OpenList.xcodeproj/project.pbxproj
client/Projects/OpenList/OpenList/Data/Repositories/DefaultCheckListRepository.swift
client/Projects/OpenList/OpenList/Data/Storages/PrivateCheckListStorage.swift
client/Projects/OpenList/OpenList/Domain/Repositories/CheckListRepository.swift
client/Projects/OpenList/OpenList/Domain/UseCases/PersistenceUseCase.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/AddCheckListItemAction.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/AddCheckListItemDiffableDataSource.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/AddCheckListItemRouter.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/AddCheckListItemViewController.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/AddCheckListItemViewFactory.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/AddCheckListItemViewModel.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListTitleScene/AddCheckListTitleViewFactory.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListTitleScene/AddCheckListTitleViewModel.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/MainCategoryScene/MainCategoryViewFactory.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/MinorCategoryScene/MinorCategoryViewFactory.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/SubCategoryScene/SubCategoryViewFactory.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTableScene/CheckListTableViewController.swift
client/Projects/OpenList/OpenList/Storage/CheckListStorage/DefaultPrivateCheckListStorage.swift
client/Projects/OpenList/OpenList/Utils/App/OpenListNotificationName.swift
client/Projects/OpenList/OpenList/Utils/App/ViewControllable.swift

- #150 
모달이 닫힐 때 이전 뷰에 이벤트를 알리는 방법을 고민했습니다.
결국 노티피케이션으로 알려서 이벤트를 반영하는 방법을 채택했습니다.
n/a
- 페어프로그래밍

생성된 체크리스트 로컬에 저장하는 기능 구현

---

client/Projects/OpenList/OpenList.xcodeproj/project.pbxproj
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/AddCheckListItemAction.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/AddCheckListItemDiffableDataSource.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/AddCheckListItemViewController.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/AddCheckListItemViewModel.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/View/AddCheckListItemButton.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/View/AddCheckListItemHeaderView.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/View/AddCheckListItemPlaceholder.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/View/AddCheckListItemTableViewHeader.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/View/AddCheckListItemTableViewSectionHeader.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/View/AiCheckListCell.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/View/SelectCheckListCell.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/MainCategoryScene/MainCategoryViewController.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/MainCategoryScene/View/SkipButton.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/MinorCategoryScene/MinorCategoryViewController.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/SubCategoryScene/SubCategoryViewController.swift

- https://github.com/boostcampwm2023/iOS10-OpenList/issues/154
DiffableDataSource와 많이 싸웠습니다 (하하)
그리고 HeaderView의 제목 정보와 태그는 로딩 전에 보여주는게 좋을 것 같아 분리했습니다
```swift
private var configureHeaderView: PassthroughSubject<Void, Never>
```
- n/a

AI 추천 체크리스트 화면 구현

---

server/docker-compose.yaml
server/src/shared-checklists/shared-checklists.gateway.ts

- #174 
- 우선은 logger가 아닌 console.log로 함 
- 추후 logger로 교체
- n/a
- n/a

[Server] 웹소켓 히스토리 버그 수정 및 콘솔 로그 추가

---

server/redis/redis.module.ts

[Server] redis 연결 버그 수정: password부분 주석처리

---

client/Projects/OpenList/OpenList.xcodeproj/project.pbxproj
client/Projects/OpenList/OpenList/DesignSystem/Sources/OpenListTextView.swift
client/Projects/OpenList/OpenList/Domain/UseCases/DetailCheckListUseCase.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/AddCheckListItemViewController.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/View/AddCheckListItemPlaceholder.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/View/AddCheckListItemTableViewSectionHeader.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/View/AiCheckListCell.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/AddTabScene/AddCheckListItemScene/View/SelectCheckListCell.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/PrivateDetailCheckListScene/PrivateDetailCheckListViewController.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/PrivateDetailCheckListScene/View/LocalCheckListItem.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/View/CheckListItemPlaceholder.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/WithDetailCheckListScene/View/WithCheckListItem.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/WithDetailCheckListScene/WithDetailCheckListViewController.swift

- #186 
- 셀이 실시간으로 늘어남에 따라 layout을 조정해야 했습니다.
|실행화면|
|-|
|<img width="300" src="https://github.com/boostcampwm2023/iOS10-OpenList/assets/53855302/2478ea3d-ad32-48e9-aace-6e86df83a7e0">|
n/a

Textfield에서 TextView로 변경

---

client/Projects/CustomNetwork/CustomNetwork/NetworkService.swift
client/Projects/CustomNetwork/CustomNetwork/URLRequestBuilder.swift
client/Projects/OpenList/OpenList.xcodeproj/project.pbxproj
client/Projects/OpenList/OpenList/Data/Repositories/DefaultWithCheckListRepository.swift
client/Projects/OpenList/OpenList/DesignSystem/Sources/CheckListEmptyView.swift
client/Projects/OpenList/OpenList/Domain/Entites/DeleteCheckListItem.swift
client/Projects/OpenList/OpenList/Domain/Repositories/CheckListRepository.swift
client/Projects/OpenList/OpenList/Domain/Repositories/WithCheckListRepository.swift
client/Projects/OpenList/OpenList/Domain/UseCases/DetailCheckListUseCase.swift
client/Projects/OpenList/OpenList/Domain/UseCases/PersistenceUseCase.swift
client/Projects/OpenList/OpenList/Domain/UseCases/WithCheckListUseCase.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTableScene/CheckListTableAction.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTableScene/CheckListTableViewController.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTableScene/CheckListTableViewModel.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/PrivateDetailCheckListScene/PrivateDetailCheckListViewModel.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/WithDetailCheckListScene/WithDetailCheckListAction.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/WithDetailCheckListScene/WithDetailCheckListViewController.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/WithDetailCheckListScene/WithDetailCheckListViewFactory.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/WithDetailCheckListScene/WithDetailCheckListViewModel.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/WithCheckListScene/WithCheckListAction.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/WithCheckListScene/WithCheckListViewController.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/WithCheckListScene/WithCheckListViewFactory.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/WithCheckListScene/WithCheckListViewModel.swift

체크리스트 삭제 API 연동

---

server/src/auth/auth.service.spec.ts
server/src/auth/auth.service.ts
server/src/shared-checklists/shared-checklists.gateway.ts

[Server] 클라이언트와 api 연동 작업 (login, socket history) 

---

client/Projects/OpenList/OpenList.xcodeproj/project.pbxproj
client/Projects/OpenList/OpenList/Data/DTO/CRDTResponseDTO.swift
client/Projects/OpenList/OpenList/Data/Repositories/DefaultCRDTRepository.swift
client/Projects/OpenList/OpenList/Domain/Entites/WithCheckListItemDetail.swift
client/Projects/OpenList/OpenList/Domain/Repositories/CRDTRepository.swift
client/Projects/OpenList/OpenList/Domain/UseCases/CRDTUseCase.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/WithDetailCheckListScene/WithDetailCheckListViewController.swift

- https://github.com/boostcampwm2023/iOS10-OpenList/issues/195
Pair Programming 진행했습니다~
- n/a
- n/a

feat: History 반영, 제목 반영

---

client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/CheckListTabViewFactory.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/RecommendTabScene/RecommendTabRouter.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/RecommendTabScene/RecommendTabViewController.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/RecommendTabScene/RecommendTabViewFactory.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/TabBarViewController.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/TabBarViewFactory.swift

- #200 
n/a
|실행화면|
|-|
|<img width="300" src="https://github.com/boostcampwm2023/iOS10-OpenList/assets/53855302/b154936c-351e-46de-bc7a-b82f7b43e044">|
n/a

피드 뷰 네비게이션 바 추가

---

client/Projects/OpenList/OpenList/Domain/UseCases/CRDTUseCase.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/WithDetailCheckListScene/View/WithCheckListItemCell.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/WithDetailCheckListScene/WithDetailCheckListViewController.swift

- #213 
- 동시편집 과정에서 체크가 안되거나, 앱이 꺼지는 오류 해결
n/a
n/a

동시편집 긴급 오류 수정

---

ai/generate-server/generate-server.js
ai/generate-server/gpt-data-saver.js
ai/generate-server/main.js
ai/generate-server/package.json
ai/generate-server/redis-sub.js
ai/generate-server/yarn.lock

#218 
- 비동기를 위해 @supercharge/promise-pool 도입
- sub client 생성할 때  환경변수 이용하도록 개선
- 변경된 db 스키마에 대해 insert문 및 구조 개선
- gpt 요청 시 에러에 대한 retry 로직 구현
N/A
N/A

[Server] 카테고리 데이터 배열 입력 처리, promise pool 방식 도입, env 방식으로 변경

---

README.md

프로젝트 소개 업데이트

---

README.md

docs: Update Reademe

---

server/src/auth/auth.service.ts

[Server] jwt 토큰 만료 시간 환경변수화

---

client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/WithDetailCheckListScene/View/WithCheckListItemCell.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/WithDetailCheckListScene/WithDetailCheckListDiffableDataSource.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/DetailScene/WithDetailCheckListScene/WithDetailCheckListViewController.swift

- #246 
**`문제상황`**
- 셀이 정상적으로 삭제되지 않는 오류
**`원인`**
- UseCase에 요청하지 않고 ViewController에서 임의로 IndexPath로 접근하여 삭제함
**`해결방법`**
- IndexPath로 접근하여 삭제하는 코드 제거
n/a
n/a

CRDT 셀 삭제 오류 수정

---

README.md

프로젝트 README 수정

---

client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/WithCheckListScene/WithCheckListCell.swift
client/Projects/OpenList/OpenList/Scenes/TabbarScene/CheckListTabScene/WithCheckListScene/WithCheckListViewController.swift

- #255 
개인셀에 있는 그림자 코드를 동일시하게 적용했습니다.
|개인셀|함께셀|
|:---:|:---:|
|<img src="https://github.com/boostcampwm2023/iOS10-OpenList/assets/48887389/13295378-09ef-4897-8cce-ef7268c706c2"/>|<img src="https://github.com/boostcampwm2023/iOS10-OpenList/assets/48887389/b4bf1353-c5a0-4ef5-9463-9c69c0a473ae"/>|
n/a

함께 셀 그림자 디자인 수정

---

.gitignore

Reverts boostcampwm2023/iOS10-OpenList#277

Revert "Server/develop AWS 서버 이전 배포"
